spring.application.name=student

# Ensure request body match
spring.jackson.deserialization.fail-on-unknown-properties=true

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rupp
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true